#!/bin/bash
apt-get update -y
apt-get install -y apache2
systemctl start apache2
systemctl enable apache2

echo "<!DOCTYPE html>
<html>
<body style='background-color:green'>
<h1>Hi Pooja Saykar this is --> Server1</h1>
</body>
</html>" > /var/www/html/index.html
